In [31]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

np.set_printoptions(6, suppress=True)

plt.style.use([
    'grid',
    'notebook'
])

In [32]:
A_vertices = []
B_vertices = []

Ts = .5

r = .31
mu = .40
sigma = .55
A2 = .3019

Kb = 15.92*10e-4

In [33]:
z1_bounds = np.array([-.5160, 2.3060])
z2_bounds = np.array([.0033, .0077])
z3_bounds = np.array([3.4478, 18.4570])

for z1 in z1_bounds:
    for z2 in z2_bounds:
        for z3 in z3_bounds:
            Ai = Ts * np.array([
                [-z1*z3, z1*z3],
                [z1/A2, -((z1+z2)/A2)]
            ]) + np.eye(2)

            Bi = Ts * np.array([
                [Kb*z3],
                [.0]
            ])

            print(
                np.linalg.eigvals(Ai)
            )

            A_vertices.append(Ai)
            B_vertices.append(Bi)

[2.741446 0.997208]
[6.615663 0.995366]
[2.737895 0.993473]
[6.614557 0.989184]
[-6.797138  0.997214]
[-24.100898   0.995366]
[-6.800713  0.993501]
[-24.102008   0.989189]


In [34]:
Z1_, Z2_, Z3_ = sp.symbols('Z1 Z2 Z3')

z1_min, z1_max = z1_bounds
z2_min, z2_max = z2_bounds
z3_min, z3_max = z3_bounds

M1 = (Z1_ - z1_min) / (z1_max - z1_min)
N1 = (Z2_ - z2_min) / (z2_max - z2_min)
P1 = (Z3_ - z3_min) / (z3_max - z3_min)

M2 = 1 - M1
N2 = 1 - N1
P2 = 1 - P1

In [35]:
print(' ')
print(M1)
print(N1)
print(P1)
print(' ')
print(M2)
print(N2)
print(P2)

 
0.354358610914245*Z1 + 0.182849043231751
227.272727272727*Z2 - 0.75
0.0666258028409242*Z3 - 0.229712443034939
 
0.817150956768249 - 0.354358610914245*Z1
1.75 - 227.272727272727*Z2
1.22971244303494 - 0.0666258028409242*Z3


In [36]:
for i in range(len(A_vertices)):
    A = A_vertices[i]
    B = B_vertices[i]
    
    np.save(f'./vertices/A_{i}', A)
    np.save(f'./vertices/B_{i}', B)

In [37]:
A_vertices

[array([[ 1.889532, -0.889532],
        [-0.854588,  1.849122]]),
 array([[ 5.761906, -4.761906],
        [-0.854588,  1.849122]]),
 array([[ 1.889532, -0.889532],
        [-0.854588,  1.841835]]),
 array([[ 5.761906, -4.761906],
        [-0.854588,  1.841835]]),
 array([[-2.975313,  3.975313],
        [ 3.819145, -2.824611]]),
 array([[-20.280921,  21.280921],
        [  3.819145,  -2.824611]]),
 array([[-2.975313,  3.975313],
        [ 3.819145, -2.831898]]),
 array([[-20.280921,  21.280921],
        [  3.819145,  -2.831898]])]